// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARYw6G1qMH5zA1KBh4WaBv4p3Y1CHf9fI',
    appId: '1:147592394614:web:fa3d12d1c03752546a2c57',
    messagingSenderId: '147592394614',
    projectId: 'heroes-2048-game-400a3',
    authDomain: 'heroes-2048-game-400a3.firebaseapp.com',
    storageBucket: 'heroes-2048-game-400a3.appspot.com',
    measurementId: 'G-QYFCF7DG2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmdEGc-lVqu79LCYXco4d-A6ER0Xakriw',
    appId: '1:147592394614:android:de526203e758fe346a2c57',
    messagingSenderId: '147592394614',
    projectId: 'heroes-2048-game-400a3',
    storageBucket: 'heroes-2048-game-400a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2zGMMYbOxVfA4eYrPZkOpYefGFnmTqmw',
    appId: '1:147592394614:ios:d52c27210d0323776a2c57',
    messagingSenderId: '147592394614',
    projectId: 'heroes-2048-game-400a3',
    storageBucket: 'heroes-2048-game-400a3.appspot.com',
    iosClientId: '147592394614-90uh917ro300ldtfjt73vbbp7e1g306m.apps.googleusercontent.com',
    iosBundleId: 'com.shakhob.heroes2048game',
  );
}
